### ISSUE TITLE
상품 상세 페이지 마크업

### ISSUE THREAD

**Issue by Oh5Yeonju** [Eurachacha/hanmogeum#113]
## 🏗 구현할 기능

상품 상세 페이지 마크업

## 🔧 상세 작업 내용
- [x] 좌측 상품 이미지, 상세정보 컨테이너 생성
- [x] 우측 상품정보 요약 및 수량카운터, 장바구니, 바로구매 버튼 컨테이너 생성

## 💬 참고 사항
카트 리코일 로직이 구현된 이후 추가적인 기능을 구현합니다.

**Comment by 0chae01** [comment]
상품상세정보는 목업 작업 후 삽입 예정입니다.
