### ISSUE TITLE
회원가입 시 비밀번호확인 input 수정 후 비밀번호 input을 동일하게 입력했을 때 에러문구 출력됨

### ISSUE THREAD

**Issue by 0chae01** [Eurachacha/hanmogeum#131]
## 🐛 버그 내용

회원가입 시 비밀번호확인 input 수정 후 비밀번호 input을 동일하게 입력했을 때 에러문구 출력됨

## 🏃🏼 버그 재현 방법
1. 비밀번호 확인 input을 먼저 입력 or 수정
2. 비밀번호 input에 동일한 값을 입력
3. 두 input에 입력한 값이 같아도 `동일한 패스워드로 입력해주세요.`문구가 출력되어 있음

## 📸 스크린샷
<img width="482" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/124250465/75e07478-cf5b-4948-b775-dddc1574f338">

**Comment by jungmyungjin** [comment]
dev에 바로 push 되어 PR 내역이 없습니다.
