### ISSUE TITLE
장바구니에 상품이 없는 상태에서 구매가 되는 버그

### ISSUE THREAD

**Issue by jungmyungjin** [Eurachacha/hanmogeum#201]
## 🐛 버그 내용
- 장바구니에 상품이 없는 경우 결제되지 않아야 하지만, 결제되는 버그

## 🏃🏼 버그 재현 방법
1. 비어있는 장바구니에서 구매하기 버튼 클릭
<img width="1136" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/36308113/5b39c06b-725c-42b6-8de6-384226b4d3ee">

2. 배송지 입력후 결제하기 버튼 클릭
<img width="1093" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/36308113/fac4a119-6522-4db7-b9bc-ad6c9074c85b">

3. 주문 완료 화면 확인
<img width="1010" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/36308113/a71cc1c8-19a4-4450-be2c-4e9941bb6618">

**Comment by 0chae01** [comment]
1. 선택상품금액이 0원인 경우 구매하기 버튼 비활성화
2. 구매하기 페이지 접속시 상품이 없으면 모달 or 에러페이지
