### ISSUE TITLE
로그인 후 URL을 직접 입력하여 주문하기로 들어가면 장바구니에 있는 페이지가 주문으로 들어오는 버그

### ISSUE THREAD

**Issue by jungmyungjin** [Eurachacha/hanmogeum#394]
## 🏃🏼 버그 재현 방법
1. 장바구니에 상품을 담는다.
2. 다음 URL을 직접 입력한다. `http://localhost:5173/orders/checkout`
3. 장바구니에 담긴 상태가 주문하기로 이동된다.

**Comment by 0chae01** [comment]
/orders/checkout 페이지에 url 입력으로 접근 시 장바구니 데이터를 불러온 구매하기 페이지가 출력됩니다.
이때 장바구니 데이터가 없으면 `잘못된 접근입니다` 모달이 나타나고 홈으로 이동합니다.
