### ISSUE TITLE
상세페이지 메인 이미지와 상세이미지의 분리가 안되어 보임

### ISSUE THREAD

**Issue by jungmyungjin** [Eurachacha/hanmogeum#461]
## 🐛 버그 내용
상세 페이지에서 메인 상품 이미지와 상세 상품이미지의 분리가 안되어 보입니다.

## 📸 스크린샷
![image](https://github.com/Eurachacha/hanmogeum/assets/36308113/5d205734-0019-429d-a65f-d4730233efcf)

**Comment by 0chae01** [comment]
- [ ] 상품 메인이미지와 상세정보 사이에 컨텐츠 삽입

**Comment by 0chae01** [comment]
해당 상품의 맛, 차 종류, 포장 형태 정보를 담아 출력합니다.
