### ISSUE TITLE
상품 상세이미지 링크가 안보이는 문제

### ISSUE THREAD

**Issue by jungmyungjin** [Eurachacha/hanmogeum#463]
## 🔩 작업 내용

**분말**
- [x] 쌉싸름한 제주 말차 : 상품 상세페이지 이미지가 호지차 이미지임

**잎차**
- [x] 세작녹차 30g
- [x] 호박차 40g
- [x] 호지차 30g

**티백**
- [x] 잔잔한 나무향의 보이숙차 티백 10ea
- [x] 고소한 옥수수 같은 감잎차 티백 (10ea)
- [x] 은은한 밀크초콜릿 같은 쑥차 티백 (10ea)
- [x] 달콤한 조청 같은 호박차 티백 (10ea)
- [x] 고소한 초콜릿향의 호지차 티백 5ea

**Comment by 0chae01** [comment]
모두 수정완료되었습니다.
