### ISSUE TITLE
로딩스피너가 헤더 위로 올라와 보이는 문제

### ISSUE THREAD

**Issue by 0chae01** [Eurachacha/hanmogeum#527]
## 🐛 버그 내용
로딩스피너가 헤더보다 위로 올라옴

## 🏃🏼 버그 재현 방법
1. 로딩스피너가 있을 때 스크롤

## 📸 스크린샷
<img width="1440" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/124250465/fd1ec14a-87ed-4fed-9eb7-4779d0896306">

**Comment by jungmyungjin** [comment]
contents 크기가 높게 잡혀있어 스크롤이 생겨서 나오는 이슈로 확인하여 App.tsx를 수정하였습니다!
