### ISSUE TITLE
git commit convention 제목 글자수가 부족한 이슈

### ISSUE THREAD

**Issue by jungmyungjin** [Eurachacha/hanmogeum#56]
## 문제 사항
<img width="762" alt="image" src="https://github.com/Eurachacha/hanmogeum/assets/36308113/03f3e598-09c7-418d-b486-9258e68027c3">
- 위와 같이 스코프의 파일 경로가 길어 질 수록 커밋 제목에 쓸 내용의 글자수가 줄어듦.

## 변경 사항
```js
# 커밋 제목
 # <커밋타입>(<스코프>): <커밋내용> (#<이슈번호>)
```
커밋 스코프에 해당하는 내용을 변경

변경 전 <스코프> : 변경되는 파일이 속한 폴더 명
변경 후 <스코프> : 커밋 변경 위치를 지정하는 모든 것

**Comment by jungmyungjin** [comment]
확인 했습니다.

**Comment by Oh5Yeonju** [comment]
확인했습니다.
