### ISSUE TITLE
일반 버튼 공통 컴포넌트 height값이 100%로 변경됨에 따른 스타일링 수정

### ISSUE THREAD

**Issue by 0chae01** [Eurachacha/hanmogeum#93]
## 🔩 작업 내용

일반 버튼 공통 컴포넌트 height값을 100%로 설정했습니다.
따라서 버튼 컴포넌트들이 사용된 곳의 스타일링이 깨질 수 있습니다. 확인바랍니다.

**Comment by jungmyungjin** [comment]
스타일링 영향 없음을 확인하였습니다.

**Comment by Oh5Yeonju** [comment]
확인했습니다
