### ISSUE TITLE
특정 한글 입력 시 글씨가 보이지 않는 이슈

### ISSUE THREAD

**Issue by 0chae01** [Eurachacha/hanmogeum#94]
## 🐛 버그 내용

한글 특정 글자 입력 시 글씨가 보이지 않고 있습니다.

## 🏃🏼 버그 재현 방법
1. input 에서 한글 입력 
2. 특정 글자 입력 시 글자가 보이지 않음
(현재 파악된 보이지 않는 글자 : 븤븥븣븦즠즡즟즢듴듵듳듶긐긑긏긒믘믙믗믚늨늩릌릋킅킃킆틐틑틏틒츸츹츷츺픜픝픛픞...)

## 📸 스크린샷

https://github.com/Eurachacha/hanmogeum/assets/124250465/59141192-30ee-49da-918a-ffdd9bd0115f

**Comment by jungmyungjin** [comment]
관련 내용 찾아 본 결과
- SUIT는 꼭 필요한 2350자 만을 추렸기 때문에 `퇕`과 같은 글자가 제외되서 만들어져서 보이지 않는것으로 보입니다.
- 아직까지의 버전에선 SUIT에서 추가 글자를 지원할 예정이 없다고합니다.
- 이와 같은 문제를 해결하기 위해서는 폰트를 변경하는 방법이 최우선 인 것 같습니다.

참고 링크
https://hanjoonkblog.blogspot.com/2017/12/blog-post.html
https://github.com/sun-typeface/SUIT/issues/1
